/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arfit.dashboard;

import java.awt.Color;

/**
 *
 * @author yunac
 */
public class Main extends javax.swing.JFrame {

    
    
    public Main() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resizeMenuBtn = new com.arfit.components.CustomizedButton();
        panelBG1 = new com.arfit.components.PanelBG();
        menu1 = new com.arfit.dashboard.Menu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resizeMenuBtn.setText("<");
        resizeMenuBtn.setBorderColor(new java.awt.Color(246, 246, 246));
        resizeMenuBtn.setColorClick(new java.awt.Color(204, 204, 204));
        resizeMenuBtn.setColorOver(new java.awt.Color(246, 246, 246));
        resizeMenuBtn.setRadius(55);
        resizeMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeMenuBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resizeMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 40, 40));

        panelBG1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelBG1Layout = new javax.swing.GroupLayout(panelBG1);
        panelBG1.setLayout(panelBG1Layout);
        panelBG1Layout.setHorizontalGroup(
            panelBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBG1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(897, Short.MAX_VALUE))
        );
        panelBG1Layout.setVerticalGroup(
            panelBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBG1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        getContentPane().add(panelBG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resizeMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeMenuBtnActionPerformed
        // TODO add your handling code here:
        if (rootPaneCheckingEnabled) {
            
        }
    }//GEN-LAST:event_resizeMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.arfit.dashboard.Menu menu1;
    private com.arfit.components.PanelBG panelBG1;
    private com.arfit.components.CustomizedButton resizeMenuBtn;
    // End of variables declaration//GEN-END:variables
}
