/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arfit.main;

import java.awt.Color;

/**
 *
 * @author yunac
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new com.arfit.components.background();
        loginidtxt = new javax.swing.JTextField();
        loginemailtxt = new javax.swing.JTextField();
        signuptxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background1.setBackground(new java.awt.Color(255, 255, 255));

        loginidtxt.setForeground(java.awt.Color.gray);
        loginidtxt.setText("Student ID");
        loginidtxt.setMargin(new java.awt.Insets(10, 10, 10, 10));
        loginidtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginidtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginidtxtFocusLost(evt);
            }
        });
        loginidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginidtxtActionPerformed(evt);
            }
        });

        loginemailtxt.setForeground(java.awt.Color.gray);
        loginemailtxt.setText("NU Email");
        loginemailtxt.setMargin(new java.awt.Insets(10, 10, 10, 10));
        loginemailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginemailtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginemailtxtFocusLost(evt);
            }
        });

        signuptxt.setForeground(java.awt.Color.gray);
        signuptxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signuptxt.setText("No Account? Sign up here.");
        signuptxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signuptxtMouseClicked(evt);
            }
        });

        jButton1.setText("Log in");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arfit/canva/images/login-txt1 (2).png"))); // NOI18N

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginemailtxt)
                            .addComponent(loginidtxt)
                            .addComponent(signuptxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(loginidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(loginemailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signuptxt)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 570, 560));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arfit/canva/images/full-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1100, 710));

        setSize(new java.awt.Dimension(1100, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginidtxtActionPerformed
        Register rgt = new Register();
        Login log = new Login();
        
        log.setVisible(false);
        this.dispose();
        rgt.setVisible(true);
    }//GEN-LAST:event_loginidtxtActionPerformed

    private void signuptxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuptxtMouseClicked
       Register rgt = new Register();
       Login log = new Login();
        
       log.setVisible(false);
       this.dispose();
       rgt.setVisible(true);
    }//GEN-LAST:event_signuptxtMouseClicked

    private void loginidtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginidtxtFocusGained
        if (loginidtxt.getText().equals("Student ID")) {
            loginidtxt.setText("");
            loginidtxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_loginidtxtFocusGained

    private void loginidtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginidtxtFocusLost
        if (loginidtxt.getText().equals("")) {
            loginidtxt.setText("Student ID");
            loginidtxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_loginidtxtFocusLost

    private void loginemailtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginemailtxtFocusGained
        if (loginemailtxt.getText().equals("NU Email")) {
            loginemailtxt.setText("");
            loginemailtxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_loginemailtxtFocusGained

    private void loginemailtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginemailtxtFocusLost
        if (loginemailtxt.getText().equals("")) {
            loginemailtxt.setText("NU Email");
            loginemailtxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_loginemailtxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.arfit.components.background background1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField loginemailtxt;
    private javax.swing.JTextField loginidtxt;
    private javax.swing.JLabel signuptxt;
    // End of variables declaration//GEN-END:variables
}
